
appl  = add_state(_('application'),                'Person', initial=True)
prop  = add_state(_('send interview proposition'), 'Person')
itne  = add_state(_('interview time negociation'), 'Person')
itpl  = add_state(_('interview planned'),          'Person')
itju  = add_state(_('interview judgment'),         'Person')
spoa  = add_state(_('send positive answer'),       'Person')
snea  = add_state(_('send negative answer'),       'Person')
refu  = add_state(_('refused'),                    'Person')
recr  = add_state(_('recruited'),                  'Person')
canc  = add_state(_('canceled'),                   'Person')

add_transition(_('cancel application'), 'Person', (appl, prop, itne, itpl, itju, spoa, snea, refu, recr),  canc)
add_transition(_('discard application'), 'Person', (appl, itju),  snea)
add_transition(_('negative answer sent'), 'Person', (snea,),  refu)
add_transition(_('propose interview'), 'Person', (appl,),  prop)
add_transition(_('schedule interview'), 'Person', (appl,),  itne)
add_transition(_('interview scheduled'), 'Person', (itne,),  itpl)
add_transition(_('interview done'), 'Person', (itpl,),  itju)
add_transition(_('propose new interview'), 'Person', (itju,),  prop)
add_transition(_('accept application'), 'Person', (itju, ),  spoa)
add_transition(_('propositiion accepted'), 'Person', (spoa,),  recr)

checkpoint()
