appl  = add_state(_('application'),                'Application', initial=True)
prop  = add_state(_('send interview proposition'), 'Application')
itne  = add_state(_('interview time negociation'), 'Application')
itpl  = add_state(_('interview planned'),          'Application')
itju  = add_state(_('interview judgment'),         'Application')
spoa  = add_state(_('send positive answer'),       'Application')
snea  = add_state(_('send negative answer'),       'Application')
refu  = add_state(_('refused'),                    'Application')
recr  = add_state(_('recruited'),                  'Application')
canc  = add_state(_('canceled'),                   'Application')

add_transition(_('cancel application'), 'Application', (appl, prop, itne, itpl, itju, spoa, snea, refu, recr),  canc)
add_transition(_('discard application'), 'Application', (appl, itju),  snea)
add_transition(_('negative answer sent'), 'Application', (snea,),  refu)
add_transition(_('propose interview'), 'Application', (appl,),  prop)
add_transition(_('schedule interview'), 'Application', (appl,),  itne)
add_transition(_('interview scheduled'), 'Application', (itne,),  itpl)
add_transition(_('interview done'), 'Application', (itpl,),  itju)
add_transition(_('propose new interview'), 'Application', (itju,),  prop)
add_transition(_('accept application'), 'Application', (itju, ),  spoa)
add_transition(_('propositiion accepted'), 'Application', (spoa,),  recr)

checkpoint()
